# Generated by Django 4.2.4 on 2023-08-27 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0003_room_creator_room_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='room',
            name='participants',
        ),
    ]
