# Generated by Django 4.2.4 on 2023-08-29 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0005_room_participants_alter_message_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='online_users',
            field=models.ManyToManyField(blank=True, related_name='online_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
