# Generated by Django 4.2.4 on 2023-08-29 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('room', '0006_room_online_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='online_users',
        ),
        migrations.AddField(
            model_name='room',
            name='connected_users',
            field=models.ManyToManyField(blank=True, related_name='connected_rooms', to=settings.AUTH_USER_MODEL),
        ),
    ]
