# Generated by Django 4.2.4 on 2023-08-29 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0009_remove_room_online_connected'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Connected',
        ),
    ]
