# Generated by Django 4.2.4 on 2023-08-29 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0011_room_is_online'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='is_online',
        ),
    ]
